times = ('Palmeiras', 'Santos', 'Flamengo', 'Atlético-MG', 'São Paulo', 'Internacional', 'Athletico-PR', 'Botafogo', 'Goiás', 'Corinthians', 'Grêmio', 'Bahia', 'Ceará', 'Fortaleza', 'Vasco', 'Cruzeiro', 'Fluminense', 'Chapecoense', 'CSA', 'Avaí')
print('-='*20)
print(f'Lista de times do Brasileirão: {times}')
print('-='*20)
print(f'Os 5 primeiros são {times[0:5]}')
print('-='*20)
print(f'Os 4 últimos são {times[-4:]}')#{times[-4:]}
print('-='*20)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-='*20)
print(f'O chapecoense está na {times.index("Chapecoense") + 1}ª posição')
